// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Logged during the processing of a Google API event being sent to a
/// message bus.
public struct GoogleApiSourceActivity: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The unique system generated ID when a message bus receives an event. This
  /// ID is propagated throughout the request.
  public var messageUid: Swift.String = Swift.String()

  /// The CloudEvent ID and source from the attributes of the event.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// The point in time when the activity occurred.
  public var activityTime: GoogleWKT.WKTTimestamp? = nil

  /// One of the activities that can be logged during the processing of a Google
  /// API event.
  public var activity: ActivityOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GoogleApiSourceActivity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GoogleApiSourceActivity().with { $0.messageUid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let messageUid = CodingKeys(stringValue: "messageUid")
    static let attributes = CodingKeys(stringValue: "attributes")
    static let activityTime = CodingKeys(stringValue: "activityTime")
    static let published = CodingKeys(stringValue: "published")

    static let _knownKeys: Set<Swift.String> = [
      "messageUid",
      "attributes",
      "activityTime",
      "published",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .messageUid) {
      self.messageUid = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .attributes)
    {
      self.attributes = value
    }
    self.activityTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .activityTime)

    var activity: ActivityOneOf? = nil
    let activityCheckAndSet = {
      if activity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'activity'"))
      }
      activity = $0
    }
    if let published = try container.decodeIfPresent(
      GoogleApiSourceActivity.Published?.self, forKey: .published)
    {
      try activityCheckAndSet(.published(published))
    }
    self.activity = activity
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.messageUid, forKey: .messageUid)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encodeIfPresent(self.activityTime, forKey: .activityTime)

    if let choice = self.activity {
      switch choice {
      case .published(let value):
        try container.encode(value, forKey: .published)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Structured log message that is emitted when an event is published to a
  /// message bus.
  public struct Published: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The message bus associated with this GoogleApiEvent configuration.
    public var messageBus: Swift.String = Swift.String()

    /// The event provider that produced the event.
    public var eventProvider: Swift.String = Swift.String()

    /// Any additional information about the event sent.
    public var details: Swift.String = Swift.String()

    /// Logged if the event encounters an error.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Published`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Published().with { $0.messageBus = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let messageBus = CodingKeys(stringValue: "messageBus")
      static let eventProvider = CodingKeys(stringValue: "eventProvider")
      static let details = CodingKeys(stringValue: "details")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "messageBus",
        "eventProvider",
        "details",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .messageBus) {
        self.messageBus = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .eventProvider) {
        self.eventProvider = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
        self.details = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.messageBus, forKey: .messageBus)
      try container.encode(self.eventProvider, forKey: .eventProvider)
      try container.encode(self.details, forKey: .details)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.GoogleApiSourceActivity.Published"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// One of the activities that can be logged during the processing of a Google
  /// API event.
  public enum ActivityOneOf: Codable, Equatable, Sendable {
    /// Logged when an event is published to a message bus.
    indirect case published(GoogleApiSourceActivity.Published?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.logging.v1.GoogleApiSourceActivity"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
