// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Logged during the processing of a message in a pipeline.
public struct PipelineActivity: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The unique system generated ID associated with the event passed from the
  /// message bus.
  public var messageUid: Swift.String = Swift.String()

  /// The CloudEvent ID and source from the attributes of the event.
  public var attributes: [Swift.String: Swift.String] = [:]

  /// The point in time when the activity occurred.
  public var activityTime: GoogleWKT.WKTTimestamp? = nil

  /// Oneof for the different logging activities in a pipeline.
  public var activity: OneOf_Activity? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PipelineActivity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PipelineActivity().with { $0.messageUid = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let messageUid = CodingKeys(stringValue: "messageUid")
    static let attributes = CodingKeys(stringValue: "attributes")
    static let activityTime = CodingKeys(stringValue: "activityTime")
    static let messageReceived = CodingKeys(stringValue: "messageReceived")
    static let messageTransformed = CodingKeys(stringValue: "messageTransformed")
    static let messageConverted = CodingKeys(stringValue: "messageConverted")
    static let messageRequestDispatched = CodingKeys(stringValue: "messageRequestDispatched")
    static let messageResponseReceived = CodingKeys(stringValue: "messageResponseReceived")

    static let _knownKeys: Set<Swift.String> = [
      "messageUid",
      "attributes",
      "activityTime",
      "messageReceived",
      "messageTransformed",
      "messageConverted",
      "messageRequestDispatched",
      "messageResponseReceived",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .messageUid) {
      self.messageUid = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .attributes)
    {
      self.attributes = value
    }
    self.activityTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .activityTime)

    var activity: OneOf_Activity? = nil
    let activityCheckAndSet = {
      if activity != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'activity'"))
      }
      activity = $0
    }
    if let messageReceived = try container.decodeIfPresent(
      PipelineActivity.MessageReceived?.self, forKey: .messageReceived)
    {
      try activityCheckAndSet(.messageReceived(messageReceived))
    }
    if let messageTransformed = try container.decodeIfPresent(
      PipelineActivity.MessageTransformed?.self, forKey: .messageTransformed)
    {
      try activityCheckAndSet(.messageTransformed(messageTransformed))
    }
    if let messageConverted = try container.decodeIfPresent(
      PipelineActivity.MessageConverted?.self, forKey: .messageConverted)
    {
      try activityCheckAndSet(.messageConverted(messageConverted))
    }
    if let messageRequestDispatched = try container.decodeIfPresent(
      PipelineActivity.MessageRequestDispatched?.self, forKey: .messageRequestDispatched)
    {
      try activityCheckAndSet(.messageRequestDispatched(messageRequestDispatched))
    }
    if let messageResponseReceived = try container.decodeIfPresent(
      PipelineActivity.MessageResponseReceived?.self, forKey: .messageResponseReceived)
    {
      try activityCheckAndSet(.messageResponseReceived(messageResponseReceived))
    }
    self.activity = activity
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.messageUid, forKey: .messageUid)
    try container.encode(self.attributes, forKey: .attributes)
    try container.encodeIfPresent(self.activityTime, forKey: .activityTime)

    if let choice = self.activity {
      switch choice {
      case .messageReceived(let value):
        try container.encode(value, forKey: .messageReceived)
      case .messageTransformed(let value):
        try container.encode(value, forKey: .messageTransformed)
      case .messageConverted(let value):
        try container.encode(value, forKey: .messageConverted)
      case .messageRequestDispatched(let value):
        try container.encode(value, forKey: .messageRequestDispatched)
      case .messageResponseReceived(let value):
        try container.encode(value, forKey: .messageResponseReceived)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Structured log that is emitted when a message is received in this Pipeline
  /// (or an error encountered).
  public struct MessageReceived: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Informational details when a message is received from a source.
    public var details: Swift.String = Swift.String()

    /// Input payload format of the message.
    public var inputPayloadFormat: PipelineActivity.PayloadFormat = PipelineActivity.PayloadFormat()

    /// Error encountered when receiving a message from a Channel, or if the
    /// message is malformed.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MessageReceived`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageReceived().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let details = CodingKeys(stringValue: "details")
      static let inputPayloadFormat = CodingKeys(stringValue: "inputPayloadFormat")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "details",
        "inputPayloadFormat",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
        self.details = value
      }
      if let value = try container.decodeIfPresent(
        PipelineActivity.PayloadFormat.self, forKey: .inputPayloadFormat)
      {
        self.inputPayloadFormat = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.details, forKey: .details)
      try container.encode(self.inputPayloadFormat, forKey: .inputPayloadFormat)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageReceived"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message is transformed during
  /// mediation (or an error encountered) in a Pipeline.
  public struct MessageTransformed: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Informational details when a message is transformed during mediation.
    public var details: Swift.String = Swift.String()

    /// Error encountered when transforming a message.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MessageTransformed`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageTransformed().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let details = CodingKeys(stringValue: "details")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "details",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
        self.details = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.details, forKey: .details)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageTransformed"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message is converted during
  /// mediation (or an error encountered) in a Pipeline.
  public struct MessageConverted: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Informational details when a message is converted during mediation.
    public var details: Swift.String = Swift.String()

    /// Input payload format of the message.
    public var inputPayloadFormat: PipelineActivity.PayloadFormat = PipelineActivity.PayloadFormat()

    /// Output payload format of the message.
    public var outputPayloadFormat: PipelineActivity.PayloadFormat =
      PipelineActivity.PayloadFormat()

    /// Error encountered when converting a message.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MessageConverted`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageConverted().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let details = CodingKeys(stringValue: "details")
      static let inputPayloadFormat = CodingKeys(stringValue: "inputPayloadFormat")
      static let outputPayloadFormat = CodingKeys(stringValue: "outputPayloadFormat")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "details",
        "inputPayloadFormat",
        "outputPayloadFormat",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
        self.details = value
      }
      if let value = try container.decodeIfPresent(
        PipelineActivity.PayloadFormat.self, forKey: .inputPayloadFormat)
      {
        self.inputPayloadFormat = value
      }
      if let value = try container.decodeIfPresent(
        PipelineActivity.PayloadFormat.self, forKey: .outputPayloadFormat)
      {
        self.outputPayloadFormat = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.details, forKey: .details)
      try container.encode(self.inputPayloadFormat, forKey: .inputPayloadFormat)
      try container.encode(self.outputPayloadFormat, forKey: .outputPayloadFormat)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageConverted"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message request is dispatched to a
  /// destination (or an error encountered) in a Pipeline.
  public struct MessageRequestDispatched: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Informational details when a message is dispatched to a destination.
    public var details: Swift.String = Swift.String()

    /// The destination where the event is sent to.
    public var destination: Swift.String = Swift.String()

    /// Error encountered before dispatching a message, e.g., malformed
    /// destination.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MessageRequestDispatched`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageRequestDispatched().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let details = CodingKeys(stringValue: "details")
      static let destination = CodingKeys(stringValue: "destination")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "details",
        "destination",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
        self.details = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .destination) {
        self.destination = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.details, forKey: .details)
      try container.encode(self.destination, forKey: .destination)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageRequestDispatched"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Structured log that is emitted when a message response (or error) is
  /// received from a destination for a message request that was dispatched
  /// earlier in a Pipeline.
  public struct MessageResponseReceived: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Informational details when a message response was received by the target,
    /// or when the request failed.
    public var details: Swift.String = Swift.String()

    /// The retry decision for the message after the response is received.
    public var retryStatus: PipelineActivity.MessageResponseReceived.RetryStatus = PipelineActivity
      .MessageResponseReceived.RetryStatus()

    /// The future time when the message request will be retried. Present if and
    /// only if the `retry_status` is `WILL_RETRY`.
    public var retryTime: GoogleWKT.WKTTimestamp? = nil

    /// The HTTP response code received with the message response.
    public var httpResponseCode: Swift.Int32 = Swift.Int32()

    /// Status of the message response received.
    public var error: GoogleRpc.Status? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MessageResponseReceived`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MessageResponseReceived().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let details = CodingKeys(stringValue: "details")
      static let retryStatus = CodingKeys(stringValue: "retryStatus")
      static let retryTime = CodingKeys(stringValue: "retryTime")
      static let httpResponseCode = CodingKeys(stringValue: "httpResponseCode")
      static let error = CodingKeys(stringValue: "error")

      static let _knownKeys: Set<Swift.String> = [
        "details",
        "retryStatus",
        "retryTime",
        "httpResponseCode",
        "error",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .details) {
        self.details = value
      }
      if let value = try container.decodeIfPresent(
        PipelineActivity.MessageResponseReceived.RetryStatus.self, forKey: .retryStatus)
      {
        self.retryStatus = value
      }
      self.retryTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .retryTime)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .httpResponseCode) {
        self.httpResponseCode = value
      }
      self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.details, forKey: .details)
      try container.encode(self.retryStatus, forKey: .retryStatus)
      try container.encodeIfPresent(self.retryTime, forKey: .retryTime)
      try container.encode(self.httpResponseCode, forKey: .httpResponseCode)
      try container.encodeIfPresent(self.error, forKey: .error)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Enum to encode the retry decision for the message after the response is
    /// received.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum RetryStatus: Codable, Equatable, Sendable {
      /// Default value. This value is unused.
      case unspecified
      /// The Pipeline will retry dispatching the message to the destination.
      case willRetry
      /// The Pipeline will not retry this message anymore.
      case retryExhausted
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .willRetry: return 1
        case .retryExhausted: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "RETRY_STATUS_UNSPECIFIED"
        case .willRetry: return "WILL_RETRY"
        case .retryExhausted: return "RETRY_EXHAUSTED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RetryStatus/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "RETRY_STATUS_UNSPECIFIED": self = .unspecified
        case "WILL_RETRY": self = .willRetry
        case "RETRY_EXHAUSTED": self = .retryExhausted
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RetryStatus/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .willRetry
        case 2: self = .retryExhausted
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("RETRY_STATUS_UNSPECIFIED")
        case .willRetry: return try container.encode("WILL_RETRY")
        case .retryExhausted: return try container.encode("RETRY_EXHAUSTED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity.MessageResponseReceived"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Format of the payload.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum PayloadFormat: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// JSON payload format.
    case json
    /// Proto payload format.
    case proto
    /// Avro payload format.
    case avro
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .json: return 1
      case .proto: return 2
      case .avro: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PAYLOAD_FORMAT_UNSPECIFIED"
      case .json: return "JSON"
      case .proto: return "PROTO"
      case .avro: return "AVRO"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PayloadFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PAYLOAD_FORMAT_UNSPECIFIED": self = .unspecified
      case "JSON": self = .json
      case "PROTO": self = .proto
      case "AVRO": self = .avro
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PayloadFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .json
      case 2: self = .proto
      case 3: self = .avro
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("PAYLOAD_FORMAT_UNSPECIFIED")
      case .json: return try container.encode("JSON")
      case .proto: return try container.encode("PROTO")
      case .avro: return try container.encode("AVRO")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Oneof for the different logging activities in a pipeline.
  public enum OneOf_Activity: Codable, Equatable, Sendable {
    /// Logging when a message is received in this Pipeline (or an error
    /// encountered).
    indirect case messageReceived(PipelineActivity.MessageReceived?)
    /// Logging when a message is transformed during mediation (or an error
    /// encountered).
    indirect case messageTransformed(PipelineActivity.MessageTransformed?)
    /// Logging when a message is converted during mediation (or an error
    /// encountered).
    indirect case messageConverted(PipelineActivity.MessageConverted?)
    /// Logging when a message request is dispatched to a destination (or an
    /// error encountered).
    indirect case messageRequestDispatched(PipelineActivity.MessageRequestDispatched?)
    /// Logging when a message response (or error) is received from a
    /// destination.
    indirect case messageResponseReceived(PipelineActivity.MessageResponseReceived?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.logging.v1.PipelineActivity"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
